### ISSUE TITLE
Problem with mongodb

### ISSUE THREAD

**Issue by adityasahugit** [Deevoluation/ALPR#8]
DeprecationWarning: insert is deprecated. Use insert_one or insert_many instead.
  col.insert(dict)
error in mongodb connection or insertion
: i am getting this error,after getting the image of no. plate in spyder,
plz help me with the process of inserting the no. of plate into mongodb

**Comment by Saqhas** [comment]
Our code requires that we manually create the database and the collection into the MongoDB first.
This error is due to the absence of the database in your MongoDB.
I have updated the code to automatically create the database if it is absent.
Please pull the changes. If still error persists feel free to contact.

Any other suggestion or feedback related to the repo will be greatly helpful.

**Comment by adityasahugit** [comment]
thanks for your answer, but acctually i want to fetch the data present in mongodb , i am not getting where it is stored

**Comment by Saqhas** [comment]
The data is stored in the mongodb database.
If you want to view the entries then the best way is to download any tool that can work with mongodb.
The best one according to me is studio3T.
The download page link is : https://studio3t.com/download/

The tutorial to work with mongodb is also given at this site.
For anymore help please contact us.
We will also try to reply as fast as possible.
